# Generated by Django 5.2.8 on 2025-12-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
