# Generated by Django 5.2.8 on 2025-12-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuariopersonalizado_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfiles/user-icon.png', null=True, upload_to='perfiles/'),
        ),
    ]
